// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d42f1d84133f180a03ad5296d75248bd"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"af60cdfce2d2c4fc41e5c1c30de96717": "1f8b08000000000000ff9c534f6f9b30143fe34ff16e4db466d2ce3d1178b4680433c756d35d9007afa93530084ca37dfb2994d0365bd5aa475beff7efe9fdd86a055f6ab3efb423502d0b04fa1241faeb04218e20e51270176fe516aa666f2c2c98674a502a0e21c4c8578984613065be274b4792fcf15b5d2c9697cc631ed5da5420712741a5f10f85235daa92e492316fb5027f700f649d29b4d3bf2afaca3cb245f7a77554e6adeefb43d3954ff8137016bdb8983882c6de9bae9ef0c5f472a6b1b96b7e937dad3f6abf9eeac9ba5c3b90f106b7d2df64701bcb9bf1093f797a0ea2f223c3837d1e7fb186b763082a9a47eaa6181df5e4e615bc1de46ceea351745535876758f1a0ed9e60cd79827efaafc97b5df534f994a6a6dee9ba3d2ebb23eddedbc739996d0ee3790c6df979704915bd0b9eee2c13f1c61777f01def6061ca255b5eb1f9ce457c7d8d029ecce4e389e7ee1411d6187181a0b2d097c8783a7520e202d00f6e40f05bc01d064a22648207182a810c4e7433d1e228f9b2696173b02c143c9b1dc4d1a967fff732ab5fb109385674fafa1b0000ffff31c8e369c7030000",
		"e290bdab89eb52bc0bb91a193648d28f": "1f8b08000000000000ff6c90416b02311085eff915efb0a052ec1f083dacd959bb50926536416f126b4805376e6bc4bf5facda22f638bcf766be79623ac553bf8d5f3e07b8e16eecb2cfa10f29cf42dc26a1984a4b300ca6f6ad5484da69651ba3711c363e8755def6e1907d3f8c2782c93ad61d2c37f33931ca0e452166346fb400a069f17c496d563ee305697f1a4f24ceda257ab64841ba92a228b0f3291e7d0c180dbb211e3e77237966c515ea76e50ae2d7abf70f9f62f825c28c6ac304d756a5a59f286034fc1ab56150a95ec166015a927296d0b2515439be591f3f94ff77456923ee946a7f4aa262d3fed5d5d4a065d3d9ee61ad14e23b0000ffff8b7b4c6192010000",
		"fd7c398a5b772f096b54d7e45a54aa41": "1f8b08000000000000ff6ccdbd0a83301846e13d57f1d6a9a538383b959a828b2926829b58fd1487fc90447bfb25a3d0f10c0f87e539ee7a5bfd18099d4bd90542b03ed28ca3c0623d3e14221cf9c57a3d9a892ed8f76d1e563294dc70147abade4af66cf94371f05ef146d6a241fd422314785f4b25912595db105c56b2d3b8b25fc3aa56bccff69ffb050000ffff106ce9c0b1000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("20191125220231-create_extension_uuid.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "fd7c398a5b772f096b54d7e45a54aa41"})
		b.SetResolver("20191125220353-create_trigger_update_timestamp.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "e290bdab89eb52bc0bb91a193648d28f"})
		b.SetResolver("20191125220555-create_table_login.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "af60cdfce2d2c4fc41e5c1c30de96717"})
		}()

	return nil
}()
